### ISSUE TITLE
Single Executable

### ISSUE THREAD

**Issue by authcompanion** [authcompanion/authcompanion#44]
Today, AuthC is distributed as a docker container image, additionally the application can be run with a simple command using Docker Compose. This feat brings a new distribution online; AuthC can be downloaded and run as a single executable. 

### Benefits
- A new user can evaluate and explore AuthC without sources (cloning the repository). 
- Deploy AuthC as a single file for increased portability with executables available across major platforms (cross-compilation).

### Compiling Executables
Deno has the ability to compile a script into a self-contained executable using [`deno compile`](https://deno.land/manual/tools/compiler) and can target Windows x64, macOS x64, macOS ARM and Linux x64

### todos
- [ ]  Build a github action to build and deploy a new set of executables on push to main. Use github cdn for the single executables. 
- [ ] When the AuthC executable is launched, generate a new [keyfile](https://github.com/authcompanion/authcompanion/blob/main/generateKey.ts) if one does not exist (key used to sign, verify JWTs). 
- [ ] All .env variables are available as [script arguments](https://deno.land/manual/tools/compiler)
- [ ]  Updated readme with download links in a table for each target platform
- [ ] Updated docs.authc site to include download links
